-- migration_security_integrity_fixes.sql
-- 2026-07 — code-review remediation (DB layer). Idempotent; safe to re-run.
--
-- ⚠️ NOTE: this was authored from the repo migration text (the review token was
-- rotated before it could be applied). Before running on prod, eyeball the live
-- policies once — some may have been hand-edited in the dashboard.
--
-- Fixes:
--   1. CRITICAL  claim self-approval / status forgery — enforce a status state
--      machine + separation-of-duties via a BEFORE trigger (RLS alone cannot
--      compare OLD vs NEW status).
--   2. CRITICAL  claim_lines: claimant could DELETE/mutate lines on already
--      approved/exported claims (USING had no status filter). Restrict to
--      draft/rejected; give assigned team heads UPDATE on submitted lines so
--      per-line approve/reject actually works for non-admins.
--   3. HIGH  claim_attachments.line_id FK was ON DELETE CASCADE (code assumed
--      SET NULL) — editing a draft silently deleted line receipts. -> SET NULL.
--   4. HIGH  claim_batches_with_team_head view ran as owner (no security_invoker)
--      -> any user could read every colleague's claim. Make it respect RLS.
--   5. MED   claim_audit_log insert was WITH CHECK(true) (forgeable for any
--      batch). Limit to batches the actor is involved in.
--   6. MED   ns_departments.charge_to / entity_code / subsidiary columns were
--      never created by any migration (schema not reproducible). Add if missing.
--   7. MED   ns_intercompany_accounts write policy referenced non-existent
--      public.user_roles -> rebuild with public.is_super_user().
--   8. LOW   revoke anon EXECUTE re-granted on set_claim_batch_no; pin is_admin
--      search_path.

BEGIN;

-- ============================================================
-- FIX 1 (CRITICAL) — claim status-transition state machine + self-approval block
-- ============================================================
CREATE OR REPLACE FUNCTION public.enforce_claim_batch_transition()
RETURNS TRIGGER
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $$
DECLARE
  v_uid          UUID    := auth.uid();
  v_is_super     BOOLEAN := public.is_super_user();
  v_is_claimant  BOOLEAN;
  v_is_team_head BOOLEAN;
BEGIN
  IF TG_OP = 'INSERT' THEN
    IF NOT v_is_super THEN
      IF NEW.claimant_user_id IS DISTINCT FROM v_uid THEN
        RAISE EXCEPTION 'claim: you can only create claims for yourself';
      END IF;
      IF NEW.status IS DISTINCT FROM 'draft' THEN
        RAISE EXCEPTION 'claim: new claims must start in draft (got %)', NEW.status;
      END IF;
      -- prevent forged batch_no / pre-filled approvals on insert
      NEW.batch_no          := NULL;   -- regenerated by trg_set_claim_batch_no
      NEW.team_head_user_id := NULL;
      NEW.team_head_signed_at := NULL;
      NEW.approver_user_id  := NULL;
      NEW.approved_at       := NULL;
      NEW.exported_at       := NULL;
      NEW.exported_by_user_id := NULL;
    END IF;
    RETURN NEW;
  END IF;

  -- UPDATE
  IF v_is_super THEN
    RETURN NEW;  -- owners / admins / super users may transition freely
  END IF;

  v_is_claimant  := (OLD.claimant_user_id = v_uid);
  v_is_team_head := EXISTS (
    SELECT 1 FROM public.team_head_assignments tha
    WHERE tha.team_head_user_id = v_uid
      AND tha.charge_to_code = OLD.charge_to_code
  );

  -- Separation of duties: never approve/export your own claim
  IF v_is_claimant AND NEW.status IN ('team_head_approved', 'approved', 'exported') THEN
    RAISE EXCEPTION 'claim: you cannot approve or export your own claim';
  END IF;

  -- Claimant editing own draft/rejected claim: may only keep draft or submit
  IF v_is_claimant AND OLD.status IN ('draft', 'rejected') THEN
    IF NEW.status NOT IN ('draft', 'submitted') THEN
      RAISE EXCEPTION 'claim: a draft/rejected claim can only move to submitted (got %)', NEW.status;
    END IF;
    RETURN NEW;
  END IF;

  -- Assigned team head on a submitted claim: approve, reject, or leave submitted
  IF v_is_team_head AND OLD.status = 'submitted' THEN
    IF NEW.status NOT IN ('team_head_approved', 'rejected', 'submitted') THEN
      RAISE EXCEPTION 'claim: a team head can only approve or reject a submitted claim';
    END IF;
    RETURN NEW;
  END IF;

  RAISE EXCEPTION 'claim: transition from % to % not permitted for this user', OLD.status, NEW.status;
END;
$$;

DROP TRIGGER IF EXISTS trg_enforce_claim_transition ON public.claim_batches;
-- Name sorts before trg_set_claim_batch_no so the batch_no NULL-out takes effect
-- before that trigger regenerates it.
CREATE TRIGGER trg_enforce_claim_transition
  BEFORE INSERT OR UPDATE ON public.claim_batches
  FOR EACH ROW EXECUTE FUNCTION public.enforce_claim_batch_transition();

REVOKE EXECUTE ON FUNCTION public.enforce_claim_batch_transition() FROM anon, public;

-- ============================================================
-- FIX 2 (CRITICAL) — claim_lines write scope
-- ============================================================
DROP POLICY IF EXISTS "claim_lines_all" ON public.claim_lines;
CREATE POLICY "claim_lines_all" ON public.claim_lines
  FOR ALL TO authenticated
  USING (
    EXISTS (SELECT 1 FROM public.claim_batches b
            WHERE b.id = claim_lines.batch_id
              AND (public.is_super_user()
                   OR (b.claimant_user_id = auth.uid() AND b.status IN ('draft', 'rejected'))))
  )
  WITH CHECK (
    EXISTS (SELECT 1 FROM public.claim_batches b
            WHERE b.id = claim_lines.batch_id
              AND (public.is_super_user()
                   OR (b.claimant_user_id = auth.uid() AND b.status IN ('draft', 'rejected'))))
  );

-- Read scope must stay BROAD — the FOR ALL USING above governs SELECT too, and
-- narrowing it to draft/rejected would hide line items from team heads (approval
-- inbox) and from claimants viewing their own submitted/approved claims. Restore
-- the original read grants as a dedicated SELECT policy (RLS policies are OR'd).
DROP POLICY IF EXISTS "claim_lines_select" ON public.claim_lines;
CREATE POLICY "claim_lines_select" ON public.claim_lines
  FOR SELECT TO authenticated
  USING (
    EXISTS (SELECT 1 FROM public.claim_batches b
            WHERE b.id = claim_lines.batch_id
              AND (public.is_super_user()
                   OR b.claimant_user_id = auth.uid()
                   OR b.team_head_user_id = auth.uid()
                   OR EXISTS (SELECT 1 FROM public.team_head_assignments tha
                              WHERE tha.team_head_user_id = auth.uid()
                                AND tha.charge_to_code = b.charge_to_code)))
  );

-- Team head may UPDATE lines (per-line approve/reject) on a submitted claim they own
DROP POLICY IF EXISTS "claim_lines_th_update" ON public.claim_lines;
CREATE POLICY "claim_lines_th_update" ON public.claim_lines
  FOR UPDATE TO authenticated
  USING (
    EXISTS (SELECT 1 FROM public.claim_batches b
            WHERE b.id = claim_lines.batch_id AND b.status = 'submitted'
              AND EXISTS (SELECT 1 FROM public.team_head_assignments tha
                          WHERE tha.team_head_user_id = auth.uid()
                            AND tha.charge_to_code = b.charge_to_code))
  )
  WITH CHECK (
    EXISTS (SELECT 1 FROM public.claim_batches b
            WHERE b.id = claim_lines.batch_id AND b.status = 'submitted'
              AND EXISTS (SELECT 1 FROM public.team_head_assignments tha
                          WHERE tha.team_head_user_id = auth.uid()
                            AND tha.charge_to_code = b.charge_to_code))
  );

-- ============================================================
-- FIX 3 (HIGH) — claim_attachments.line_id FK CASCADE -> SET NULL
-- ============================================================
DO $$
DECLARE c TEXT;
BEGIN
  IF EXISTS (SELECT 1 FROM information_schema.columns
             WHERE table_schema = 'public' AND table_name = 'claim_attachments'
               AND column_name = 'line_id') THEN
    FOR c IN
      SELECT conname FROM pg_constraint
      WHERE conrelid = 'public.claim_attachments'::regclass AND contype = 'f'
        AND pg_get_constraintdef(oid) ILIKE '%(line_id)%'
    LOOP
      EXECUTE format('ALTER TABLE public.claim_attachments DROP CONSTRAINT %I', c);
    END LOOP;
    ALTER TABLE public.claim_attachments
      ADD CONSTRAINT claim_attachments_line_id_setnull
      FOREIGN KEY (line_id) REFERENCES public.claim_lines(id) ON DELETE SET NULL;
  END IF;
EXCEPTION WHEN duplicate_object THEN NULL;
END $$;

-- ============================================================
-- FIX 4 (HIGH) — view must respect the caller's RLS (Postgres 15+)
-- ============================================================
ALTER VIEW public.claim_batches_with_team_head SET (security_invoker = on);

-- ============================================================
-- FIX 5 (MED) — audit log: limit inserts to batches the actor is involved in
-- ============================================================
DROP POLICY IF EXISTS "claim_audit_log_insert" ON public.claim_audit_log;
CREATE POLICY "claim_audit_log_insert" ON public.claim_audit_log
  FOR INSERT TO authenticated
  WITH CHECK (
    public.is_super_user()
    OR EXISTS (
      SELECT 1 FROM public.claim_batches b
      WHERE b.id = claim_audit_log.batch_id
        AND (b.claimant_user_id = auth.uid()
             OR b.team_head_user_id = auth.uid()
             OR EXISTS (SELECT 1 FROM public.team_head_assignments tha
                        WHERE tha.team_head_user_id = auth.uid()
                          AND tha.charge_to_code = b.charge_to_code))
    )
  );

-- ============================================================
-- FIX 6 (MED) — ns_departments reproducible columns (no-op if already present)
-- ============================================================
ALTER TABLE public.ns_departments
  ADD COLUMN IF NOT EXISTS charge_to            TEXT,
  ADD COLUMN IF NOT EXISTS entity_code          TEXT,
  ADD COLUMN IF NOT EXISTS subsidiary_name      TEXT,
  ADD COLUMN IF NOT EXISTS subsidiary_full_name TEXT,
  ADD COLUMN IF NOT EXISTS ns_subsidiary        TEXT;

-- ============================================================
-- FIX 7 (MED) — ns_intercompany_accounts write policy (was referencing user_roles).
-- Guarded: this table is not present on every project (the intercompany feature
-- may not be deployed). Skip if absent so the rest of the migration still applies.
-- ============================================================
DO $$
BEGIN
  IF to_regclass('public.ns_intercompany_accounts') IS NOT NULL THEN
    EXECUTE 'DROP POLICY IF EXISTS "ic_accounts_write_admin" ON public.ns_intercompany_accounts';
    EXECUTE 'CREATE POLICY "ic_accounts_write_admin" ON public.ns_intercompany_accounts
               FOR ALL TO authenticated
               USING (public.is_super_user())
               WITH CHECK (public.is_super_user())';
    RAISE NOTICE 'Applied ic_accounts_write_admin policy';
  ELSE
    RAISE NOTICE 'Skipped: public.ns_intercompany_accounts does not exist (intercompany feature not deployed here)';
  END IF;
END $$;

-- ============================================================
-- FIX 8 (LOW) — undo anon EXECUTE re-grant; pin is_admin search_path
-- ============================================================
DO $$
BEGIN
  IF EXISTS (SELECT 1 FROM pg_proc WHERE pronamespace = 'public'::regnamespace AND proname = 'set_claim_batch_no') THEN
    EXECUTE 'REVOKE EXECUTE ON FUNCTION public.set_claim_batch_no() FROM anon, public';
  END IF;
  IF EXISTS (SELECT 1 FROM pg_proc WHERE pronamespace = 'public'::regnamespace AND proname = 'is_admin') THEN
    EXECUTE 'ALTER FUNCTION public.is_admin() SET search_path = public';
  END IF;
END $$;

COMMIT;

-- ============================================================
-- Verify (run after commit)
-- ============================================================
-- Expect trg_enforce_claim_transition present:
SELECT tgname FROM pg_trigger
WHERE tgrelid = 'public.claim_batches'::regclass AND NOT tgisinternal
ORDER BY tgname;
-- Expect claim_lines_all + claim_lines_th_update; audit insert with a real CHECK:
SELECT tablename, policyname, cmd FROM pg_policies
WHERE schemaname = 'public' AND tablename IN ('claim_lines', 'claim_audit_log', 'ns_intercompany_accounts')
ORDER BY tablename, policyname;
-- Expect security_invoker=on:
SELECT relname, reloptions FROM pg_class WHERE oid = 'public.claim_batches_with_team_head'::regclass;
