-- Edge Functions (service role) 同 DB admin session 更新 claim_batches 時，
-- auth.uid() 係 null → is_super_user() false → migration 36 嘅「已簽批只限 owner/admin」
-- 檢查會 raise，令 netsuite-post-vendor-bill 入完數之後改唔到 status = exported
-- (PAY-202609-0001：NetSuite bill 68892 已建立，但 CardRecon 仍然係 approved)。
-- 修正：service_role JWT 或 postgres/supabase_admin session 一律當 super user。

create or replace function public.enforce_claim_batch_transition()
returns trigger
language plpgsql
security definer
set search_path = public
as $$
declare
  v_uid          uuid    := auth.uid();
  v_is_super     boolean := public.is_super_user()
                            or coalesce(auth.role(), '') = 'service_role'
                            or session_user in ('postgres', 'supabase_admin');
  v_is_claimant  boolean;
  v_is_team_head boolean;
begin
  if TG_OP = 'INSERT' then
    if not v_is_super then
      if new.claimant_user_id is distinct from v_uid then
        raise exception 'claim: you can only create claims for yourself';
      end if;
      if new.status is distinct from 'draft' then
        raise exception 'claim: new claims must start in draft (got %)', new.status;
      end if;
      if new.is_pre_approved then
        raise exception 'claim: pre-approved payments are owner/admin only';
      end if;
      new.batch_no            := null;   -- regenerated by trg_set_claim_batch_no
      new.team_head_user_id   := null;
      new.team_head_signed_at := null;
      new.approver_user_id    := null;
      new.approved_at         := null;
      new.exported_at         := null;
      new.exported_by_user_id := null;
    end if;
    return new;
  end if;

  -- UPDATE
  if v_is_super then
    return new;
  end if;

  -- 已簽批付款只限 owner/admin：非 super user 唔可以掂 (包括改 flag)
  if old.is_pre_approved or new.is_pre_approved then
    raise exception 'claim: pre-approved payments are owner/admin only';
  end if;

  v_is_claimant  := (old.claimant_user_id = v_uid);
  v_is_team_head := exists (
    select 1 from public.team_head_assignments tha
    where tha.team_head_user_id = v_uid
      and tha.charge_to_code = old.charge_to_code
  );

  if v_is_claimant and new.status in ('team_head_approved', 'approved', 'exported') then
    raise exception 'claim: you cannot approve or export your own claim';
  end if;

  if v_is_claimant and old.status in ('draft', 'rejected') then
    if new.status not in ('draft', 'submitted') then
      raise exception 'claim: a draft/rejected claim can only move to submitted (got %)', new.status;
    end if;
    return new;
  end if;

  if v_is_team_head and old.status = 'submitted' then
    if new.status not in ('team_head_approved', 'rejected', 'submitted') then
      raise exception 'claim: a team head can only approve or reject a submitted claim';
    end if;
    return new;
  end if;

  raise exception 'claim: transition from % to % not permitted for this user', old.status, new.status;
end;
$$;
revoke execute on function public.enforce_claim_batch_transition() from anon, authenticated, public;
