-- 已簽批付款 (Pre-approved payment)：提交後可修改
--
-- 已簽批單提交後即刻自動 approved，但入 NetSuite 前同事可能要改資料
-- (發票號 / 金額 / 明細 / 附件)。允許申請人將自己嘅已簽批付款單由
-- submitted / approved 退返 draft (reopen)，改完再提交 → 再自動批核。
-- 已經入咗 NetSuite (status = exported / exported_at 有值) 就唔可以再改。
--
-- 1. 狀態機 trigger：claimant + payment + is_pre_approved +
--    old.status in (submitted, approved) + 未 export → new.status = 'draft'
--    (同時清走 approver / approved_at，等重新提交再蓋)
-- 2. RLS claim_batches_update：申請人可以 update 自己 approved 嘅已簽批付款單
--    (submitted 分支 migration 34 已有)

create or replace function public.enforce_claim_batch_transition()
returns trigger
language plpgsql
security definer
set search_path = public
as $$
declare
  v_uid          uuid    := auth.uid();
  v_is_super     boolean := public.is_super_user();
  v_is_claimant  boolean;
  v_is_team_head boolean;
begin
  if TG_OP = 'INSERT' then
    if not v_is_super then
      if new.claimant_user_id is distinct from v_uid then
        raise exception 'claim: you can only create claims for yourself';
      end if;
      if new.status is distinct from 'draft' then
        raise exception 'claim: new claims must start in draft (got %)', new.status;
      end if;
      new.batch_no            := null;   -- regenerated by trg_set_claim_batch_no
      new.team_head_user_id   := null;
      new.team_head_signed_at := null;
      new.approver_user_id    := null;
      new.approved_at         := null;
      new.exported_at         := null;
      new.exported_by_user_id := null;
    end if;
    return new;
  end if;

  -- UPDATE
  if v_is_super then
    return new;
  end if;

  -- 已簽批 flag 提交咗之後唔可以改 (防止普通單提交後自己改 flag 自批)
  if new.is_pre_approved is distinct from old.is_pre_approved and old.status <> 'draft' then
    raise exception 'claim: pre-approved flag cannot change after submission';
  end if;

  v_is_claimant  := (old.claimant_user_id = v_uid);
  v_is_team_head := exists (
    select 1 from public.team_head_assignments tha
    where tha.team_head_user_id = v_uid
      and tha.charge_to_code = old.charge_to_code
  );

  -- 已簽批付款 (老闆紙上簽名)：申請人提交後即刻自批 approved，唔使審批
  if v_is_claimant
     and old.claim_type = 'payment'
     and old.is_pre_approved and new.is_pre_approved
     and old.status = 'submitted' and new.status = 'approved' then
    return new;
  end if;

  -- 已簽批付款：提交後 (submitted / approved) 未入 NetSuite 前，申請人可以
  -- 退返 draft 修改，改完再提交會再自動批核
  if v_is_claimant
     and old.claim_type = 'payment'
     and old.is_pre_approved and new.is_pre_approved
     and old.status in ('submitted', 'approved')
     and old.exported_at is null
     and new.status = 'draft' then
    new.approver_user_id := null;
    new.approved_at      := null;
    new.approver_comment := null;
    new.exported_at      := null;
    new.exported_by_user_id := null;
    return new;
  end if;

  if v_is_claimant and new.status in ('team_head_approved', 'approved', 'exported') then
    raise exception 'claim: you cannot approve or export your own claim';
  end if;

  if v_is_claimant and old.status in ('draft', 'rejected') then
    if new.status not in ('draft', 'submitted') then
      raise exception 'claim: a draft/rejected claim can only move to submitted (got %)', new.status;
    end if;
    return new;
  end if;

  if v_is_team_head and old.status = 'submitted' then
    if new.status not in ('team_head_approved', 'rejected', 'submitted') then
      raise exception 'claim: a team head can only approve or reject a submitted claim';
    end if;
    return new;
  end if;

  raise exception 'claim: transition from % to % not permitted for this user', old.status, new.status;
end;
$$;
revoke execute on function public.enforce_claim_batch_transition() from anon, authenticated, public;

-- ---- RLS update policy：加 pre-approved approved (未 export) reopen 分支 ----
drop policy if exists "claim_batches_update" on public.claim_batches;
create policy "claim_batches_update" on public.claim_batches
  for update to authenticated
  using (
    public.is_super_user()
    or (claimant_user_id = auth.uid() and status in ('draft', 'rejected'))
    or (claimant_user_id = auth.uid() and status in ('submitted', 'approved')
        and is_pre_approved and claim_type = 'payment' and exported_at is null)
    or (
      status = 'submitted'
      and exists (
        select 1 from public.team_head_assignments tha
        where tha.team_head_user_id = auth.uid()
          and tha.charge_to_code = claim_batches.charge_to_code
      )
    )
  )
  with check (
    public.is_super_user()
    or claimant_user_id = auth.uid()
    or exists (
      select 1 from public.team_head_assignments tha
      where tha.team_head_user_id = auth.uid()
        and tha.charge_to_code = claim_batches.charge_to_code
    )
  );
