-- 已簽批付款 (Pre-approved payment) 只限 owner / admin 使用
--
-- 老闆紙上簽名批准嘅付款單，由 admin/owner 直接入 app、免審批、自批、入 NetSuite。
-- 普通同事唔應該可以建立 / 修改 / 自批已簽批單 (否則等於自己批自己)。
--
-- 1. 狀態機 trigger：
--    - INSERT：非 super user 唔可以建 is_pre_approved = true 嘅單
--    - UPDATE：非 super user 唔可以掂任何 is_pre_approved 單 (old 或 new 係 true)
--    - 之前 migration 34 / 35 加嘅「申請人自批 / reopen」fast path 拎走
--      (super user 本身 bypass trigger，唔需要)
-- 2. RLS：claim_batches_insert 非 super 只准 is_pre_approved = false；
--    claim_batches_update 回復 migration 6 形態 (super / 申請人 draft-rejected / team head submitted)

create or replace function public.enforce_claim_batch_transition()
returns trigger
language plpgsql
security definer
set search_path = public
as $$
declare
  v_uid          uuid    := auth.uid();
  v_is_super     boolean := public.is_super_user();
  v_is_claimant  boolean;
  v_is_team_head boolean;
begin
  if TG_OP = 'INSERT' then
    if not v_is_super then
      if new.claimant_user_id is distinct from v_uid then
        raise exception 'claim: you can only create claims for yourself';
      end if;
      if new.status is distinct from 'draft' then
        raise exception 'claim: new claims must start in draft (got %)', new.status;
      end if;
      if new.is_pre_approved then
        raise exception 'claim: pre-approved payments are owner/admin only';
      end if;
      new.batch_no            := null;   -- regenerated by trg_set_claim_batch_no
      new.team_head_user_id   := null;
      new.team_head_signed_at := null;
      new.approver_user_id    := null;
      new.approved_at         := null;
      new.exported_at         := null;
      new.exported_by_user_id := null;
    end if;
    return new;
  end if;

  -- UPDATE
  if v_is_super then
    return new;
  end if;

  -- 已簽批付款只限 owner/admin：非 super user 唔可以掂 (包括改 flag)
  if old.is_pre_approved or new.is_pre_approved then
    raise exception 'claim: pre-approved payments are owner/admin only';
  end if;

  v_is_claimant  := (old.claimant_user_id = v_uid);
  v_is_team_head := exists (
    select 1 from public.team_head_assignments tha
    where tha.team_head_user_id = v_uid
      and tha.charge_to_code = old.charge_to_code
  );

  if v_is_claimant and new.status in ('team_head_approved', 'approved', 'exported') then
    raise exception 'claim: you cannot approve or export your own claim';
  end if;

  if v_is_claimant and old.status in ('draft', 'rejected') then
    if new.status not in ('draft', 'submitted') then
      raise exception 'claim: a draft/rejected claim can only move to submitted (got %)', new.status;
    end if;
    return new;
  end if;

  if v_is_team_head and old.status = 'submitted' then
    if new.status not in ('team_head_approved', 'rejected', 'submitted') then
      raise exception 'claim: a team head can only approve or reject a submitted claim';
    end if;
    return new;
  end if;

  raise exception 'claim: transition from % to % not permitted for this user', old.status, new.status;
end;
$$;
revoke execute on function public.enforce_claim_batch_transition() from anon, authenticated, public;

-- ---- RLS ----
drop policy if exists "claim_batches_insert" on public.claim_batches;
create policy "claim_batches_insert" on public.claim_batches
  for insert to authenticated
  with check (
    public.is_super_user()
    or (claimant_user_id = auth.uid() and not is_pre_approved)
  );

drop policy if exists "claim_batches_update" on public.claim_batches;
create policy "claim_batches_update" on public.claim_batches
  for update to authenticated
  using (
    public.is_super_user()
    or (claimant_user_id = auth.uid() and status in ('draft', 'rejected') and not is_pre_approved)
    or (
      status = 'submitted'
      and not is_pre_approved
      and exists (
        select 1 from public.team_head_assignments tha
        where tha.team_head_user_id = auth.uid()
          and tha.charge_to_code = claim_batches.charge_to_code
      )
    )
  )
  with check (
    public.is_super_user()
    or claimant_user_id = auth.uid()
    or exists (
      select 1 from public.team_head_assignments tha
      where tha.team_head_user_id = auth.uid()
        and tha.charge_to_code = claim_batches.charge_to_code
    )
  );
