-- 已簽批付款 (Pre-approved payment requisition)：
-- 老闆已經喺紙上簽名批准嘅供應商 / 自由工作者付款，同事喺 app 上載發票 +
-- 跟付款申請版面入資料，提交後唔使再經審批 — 直接變 approved，喺
-- 「付款申請 Export」入 NetSuite (Vendor Bills)。
--
-- 1. claim_batches.is_pre_approved flag (新建時由入口決定，提交後唔可以改)
-- 2. 狀態機 trigger：pre-approved payment 申請人自己可以 submitted → approved
--    (submitted 一步照行，等 enforce_claim_submission_rules 嘅發票/查重驗證生效)
-- 3. RLS update policy：申請人可以 update 自己 submitted 嘅 pre-approved batch
-- 4. b.* view 再 recreate 令新欄出現

alter table public.claim_batches
  add column if not exists is_pre_approved boolean not null default false;

-- ---- view ----
drop view if exists public.claim_batches_with_team_head;
create view public.claim_batches_with_team_head as
select
  b.*,
  (
    select u.user_id from public.team_head_assignments tha
    join public.user_profiles u on u.user_id = tha.team_head_user_id
    where tha.charge_to_code = b.charge_to_code limit 1
  ) as assigned_team_head_user_id,
  (
    select u.full_name from public.team_head_assignments tha
    join public.user_profiles u on u.user_id = tha.team_head_user_id
    where tha.charge_to_code = b.charge_to_code limit 1
  ) as assigned_team_head_name,
  (
    select u.email from public.team_head_assignments tha
    join public.user_profiles u on u.user_id = tha.team_head_user_id
    where tha.charge_to_code = b.charge_to_code limit 1
  ) as assigned_team_head_email
from public.claim_batches b;
alter view public.claim_batches_with_team_head set (security_invoker = on);
grant select on public.claim_batches_with_team_head to authenticated;

-- ---- 狀態機 trigger ----
create or replace function public.enforce_claim_batch_transition()
returns trigger
language plpgsql
security definer
set search_path = public
as $$
declare
  v_uid          uuid    := auth.uid();
  v_is_super     boolean := public.is_super_user();
  v_is_claimant  boolean;
  v_is_team_head boolean;
begin
  if TG_OP = 'INSERT' then
    if not v_is_super then
      if new.claimant_user_id is distinct from v_uid then
        raise exception 'claim: you can only create claims for yourself';
      end if;
      if new.status is distinct from 'draft' then
        raise exception 'claim: new claims must start in draft (got %)', new.status;
      end if;
      new.batch_no            := null;   -- regenerated by trg_set_claim_batch_no
      new.team_head_user_id   := null;
      new.team_head_signed_at := null;
      new.approver_user_id    := null;
      new.approved_at         := null;
      new.exported_at         := null;
      new.exported_by_user_id := null;
    end if;
    return new;
  end if;

  -- UPDATE
  if v_is_super then
    return new;
  end if;

  -- 已簽批 flag 提交咗之後唔可以改 (防止普通單提交後自己改 flag 自批)
  if new.is_pre_approved is distinct from old.is_pre_approved and old.status <> 'draft' then
    raise exception 'claim: pre-approved flag cannot change after submission';
  end if;

  v_is_claimant  := (old.claimant_user_id = v_uid);
  v_is_team_head := exists (
    select 1 from public.team_head_assignments tha
    where tha.team_head_user_id = v_uid
      and tha.charge_to_code = old.charge_to_code
  );

  -- 已簽批付款 (老闆紙上簽名)：申請人提交後即刻自批 approved，唔使審批
  if v_is_claimant
     and old.claim_type = 'payment'
     and old.is_pre_approved and new.is_pre_approved
     and old.status = 'submitted' and new.status = 'approved' then
    return new;
  end if;

  if v_is_claimant and new.status in ('team_head_approved', 'approved', 'exported') then
    raise exception 'claim: you cannot approve or export your own claim';
  end if;

  if v_is_claimant and old.status in ('draft', 'rejected') then
    if new.status not in ('draft', 'submitted') then
      raise exception 'claim: a draft/rejected claim can only move to submitted (got %)', new.status;
    end if;
    return new;
  end if;

  if v_is_team_head and old.status = 'submitted' then
    if new.status not in ('team_head_approved', 'rejected', 'submitted') then
      raise exception 'claim: a team head can only approve or reject a submitted claim';
    end if;
    return new;
  end if;

  raise exception 'claim: transition from % to % not permitted for this user', old.status, new.status;
end;
$$;
revoke execute on function public.enforce_claim_batch_transition() from anon, authenticated, public;

-- ---- RLS update policy：加 pre-approved 申請人自批分支 ----
drop policy if exists "claim_batches_update" on public.claim_batches;
create policy "claim_batches_update" on public.claim_batches
  for update to authenticated
  using (
    public.is_super_user()
    or (claimant_user_id = auth.uid() and status in ('draft', 'rejected'))
    or (claimant_user_id = auth.uid() and status = 'submitted' and is_pre_approved and claim_type = 'payment')
    or (
      status = 'submitted'
      and exists (
        select 1 from public.team_head_assignments tha
        where tha.team_head_user_id = auth.uid()
          and tha.charge_to_code = claim_batches.charge_to_code
      )
    )
  )
  with check (
    public.is_super_user()
    or claimant_user_id = auth.uid()
    or exists (
      select 1 from public.team_head_assignments tha
      where tha.team_head_user_id = auth.uid()
        and tha.charge_to_code = claim_batches.charge_to_code
    )
  );
